version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 323146836662.dkr.ecr.us-east-2.amazonaws.com

  build:
    commands:
      - docker build -t frontend-app -f frontend/Dockerfile frontend
      - docker build -t backend-app -f backend/Dockerfile backend

  post_build:
    commands:
      - docker images
